### ISSUE TITLE
Question about Reproducing Figure 1 Results for Layer 1

### ISSUE THREAD

**Issue by dongjiancheng77** [tonychenxyz/selfie#7]
Thank you for sharing your work and code! I have been studying your paper and trying to reproduce the results shown in Figure 1, particularly for Layer 1, where the representations for words such as "mountain" and "earth" are visualized. However, I encountered some difficulties replicating the results as shown in the figure. Despite following the provided instructions and methodology as closely as possible, I couldn't observe similar representations for words like "mountain" and "earth" in Layer 1. Could you confirm if this is expected behavior, or if there might be additional preprocessing or settings required? Additionally, I am particularly concerned about the role of the [INST] token. Is it possible that my understanding or implementation of its function might be incorrect? If [INST] plays a significant role in generating these results, could you clarify how it should be applied? I would greatly appreciate any insights or guidance on these points. Thank you in advance for your time and support!

**Comment by tonychenxyz** [comment]
Hi! Sorry for the confusions. Figure 1 is for illustrative purpose, so we truncated explanations and only drew limited number of layers due to space constraint. All results in Figure 3 are reproducible.

[INST] tag is what llama-2 used to indicate user instruction. You can just wrap [INST] [/INST] around user instructions. See https://www.llama.com/docs/model-cards-and-prompt-formats/meta-llama-2/
